// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGr2SJrOzjcw1opSC8x_skD3t6OAVgbnM',
    appId: '1:850095074938:web:2a64250f2d112a22a795c3',
    messagingSenderId: '850095074938',
    projectId: 'buddy-394414',
    authDomain: 'buddy-394414.firebaseapp.com',
    storageBucket: 'buddy-394414.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGPgXiP7BfsF57fEvmh7LyRF4kC2Qvd9A',
    appId: '1:850095074938:android:1dd6bc1493f83563a795c3',
    messagingSenderId: '850095074938',
    projectId: 'buddy-394414',
    storageBucket: 'buddy-394414.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPTkbm3WsW8CBRSinn-nt17bSto6dwT2M',
    appId: '1:850095074938:ios:10bc41a5604f0b5aa795c3',
    messagingSenderId: '850095074938',
    projectId: 'buddy-394414',
    storageBucket: 'buddy-394414.firebasestorage.app',
    iosClientId: '850095074938-8om6vs236fsl0m18pu2m55rot8u1ue0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.veggies',
  );
}
